//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akumina.WebParts.Banner.Banner {
    using System.Linq;
    using System.Web.Security;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;
    using System.Web.UI.WebControls;
    using System.Xml.Linq;
    using System.Web.UI;
    using System.Web.UI.HtmlControls;
    using System.Web;
    using System.Configuration;
    using System;
    using System.Text;
    using System.Web.Profile;
    using System.Web.Caching;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.WebControls.Expressions;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    using System.Web.DynamicData;
    using System.CodeDom.Compiler;
    
    
    public partial class Banner {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal @__searchCrawlFeed;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litTop;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litDivID;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litUniqueId;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litItemsResult;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litTemplates;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litProperties;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litDebug;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(Banner target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControl__searchCrawlFeed() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.@__searchCrawlFeed = @__ctrl;
            @__ctrl.ID = "__searchCrawlFeed";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitTop() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litTop = @__ctrl;
            @__ctrl.ID = "litTop";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitDivID() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litDivID = @__ctrl;
            @__ctrl.ID = "litDivID";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitUniqueId() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litUniqueId = @__ctrl;
            @__ctrl.ID = "litUniqueId";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitItemsResult() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litItemsResult = @__ctrl;
            @__ctrl.ID = "litItemsResult";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitTemplates() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litTemplates = @__ctrl;
            @__ctrl.ID = "litTemplates";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitProperties() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litProperties = @__ctrl;
            @__ctrl.ID = "litProperties";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitDebug() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litDebug = @__ctrl;
            @__ctrl.ID = "litDebug";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::Akumina.WebParts.Banner.Banner.Banner @__ctrl) {
            global::System.Web.UI.WebControls.Literal @__ctrl1;
            @__ctrl1 = this.@__BuildControl__searchCrawlFeed();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.Literal @__ctrl2;
            @__ctrl2 = this.@__BuildControllitTop();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.Literal @__ctrl3;
            @__ctrl3 = this.@__BuildControllitDivID();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.Literal @__ctrl4;
            @__ctrl4 = this.@__BuildControllitUniqueId();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::System.Web.UI.WebControls.Literal @__ctrl5;
            @__ctrl5 = this.@__BuildControllitItemsResult();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::System.Web.UI.WebControls.Literal @__ctrl6;
            @__ctrl6 = this.@__BuildControllitTemplates();
            @__parser.AddParsedSubObject(@__ctrl6);
            global::System.Web.UI.WebControls.Literal @__ctrl7;
            @__ctrl7 = this.@__BuildControllitProperties();
            @__parser.AddParsedSubObject(@__ctrl7);
            global::System.Web.UI.WebControls.Literal @__ctrl8;
            @__ctrl8 = this.@__BuildControllitDebug();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n<script type=\"text/javascript\">\r\n    if (Akumina === undefined) {\r\n        var " +
                    "Akumina = {};\r\n    }\r\n    if (Akumina.InterAction === undefined) {\r\n        Akum" +
                    "ina.InterAction = {};\r\n    }\r\n</script>\r\n\r\n");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n\r\n<div id=\"div");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\" class=\"interAction\">\r\n    \r\n</div>\r\n<input type=\"hidden\" id=\"_ispostback\" value" +
                    "=\"");
                                     @__w.Write(Page.IsPostBack.ToString());

            @__w.Write("\" />\r\n<script type=\"text/javascript\">\r\n    \r\n    if (Akumina.InterAction.Banner =" +
                    "== undefined) {\r\n      \r\n        Akumina.InterAction.Banner = function() {\r\n    " +
                    "        this.targetDiv = \"\";\r\n            this.uniqueId = \"\";\r\n            this." +
                    "searchResults = {};\r\n            this.itemsResult  = {};\r\n            this.templ" +
                    "ateJson = {};\r\n            this.webPartTheme = \"\";\r\n            this.bannerResul" +
                    "tSource = \"\";\r\n            this.linkButtonTheme = \"\";\r\n            this.linkButt" +
                    "onTextTheme = \"\";\r\n            this.slideDuration = 3000;\r\n            this.tran" +
                    "sitionEffect = \"fade\";\r\n            this.showNavigator = true;\r\n            this" +
                    ".autoPlay = true;\r\n            this.infiniteLoop = true;\r\n            this.MaxSl" +
                    "ideCount = -1;\r\n\r\n            this.getSearchResultsUsingREST = function(me) {\r\n " +
                    "               var results = me.itemsResult;\r\n\r\n                if (results.leng" +
                    "th == 0) {\r\n                    $(me.targetDiv).html(\"\");\r\n                } els" +
                    "e {\r\n                    var heroTemplate = me.templateJson.ControlTemplate;\r\n  " +
                    "                  var liTemplate = me.templateJson.ItemTemplate;\r\n              " +
                    "      var heroContainer = $(heroTemplate);\r\n                    $(me.targetDiv)." +
                    "append(heroContainer);\r\n\r\n                    results = results.sort(function(ob" +
                    "j1, obj2) {                       \r\n                        return obj1.BannerIt" +
                    "emOrderOWSNMBR - obj2.BannerItemOrderOWSNMBR;\r\n                    });\r\n\r\n      " +
                    "              $.each(results, function(index, result) {\r\n                       " +
                    " var resultJson = {};\r\n                        resultJson.BannerHeadingOWSTEXT =" +
                    " result.BannerHeadingOWSTEXT;\r\n                        if(typeof me.H1MaxCharact" +
                    "ers != \'undefined\' && me.H1MaxCharacters > 0) {\r\n                            if(" +
                    "resultJson.BannerHeadingOWSTEXT !=null)\r\n                                resultJ" +
                    "son.BannerHeadingOWSTEXT = resultJson.BannerHeadingOWSTEXT.substring(0, me.H1Max" +
                    "Characters);\r\n                        }\r\n                        resultJson.Bann" +
                    "erImageAltTextOWSTEXT = result.BannerImageAltTextOWSTEXT;\r\n                     " +
                    "   resultJson.BannerImageOWSURLH = result.BannerImageOWSURLH;\r\n                 " +
                    "       var imgUrl = new String(resultJson.BannerImageOWSURLH);\r\n                " +
                    "        if (imgUrl.indexOf(\",\") > -1) {\r\n                            imgUrl = im" +
                    "gUrl.substring(0, imgUrl.indexOf(\",\"));\r\n                        }\r\n            " +
                    "            resultJson.BannerImageOWSURLH = imgUrl;\r\n\r\n                        r" +
                    "esultJson.BannerItemOrderOWSNMBR = result.BannerItemOrderOWSNMBR;\r\n             " +
                    "           resultJson.BannerLinkHoverTextOWSTEXT = result.BannerLinkHoverTextOWS" +
                    "TEXT;\r\n                        resultJson.BannerLinkTargetOWSCHCS = result.Banne" +
                    "rLinkTargetOWSCHCS;\r\n                        if (resultJson.BannerLinkTargetOWSC" +
                    "HCS == \"New Window\") {\r\n                            resultJson.BannerLinkTargetO" +
                    "WSCHCS = \"_blank\";\r\n                        } else {\r\n                          " +
                    "  resultJson.BannerLinkTargetOWSCHCS = \"_self\";\r\n                        }\r\n    " +
                    "                    resultJson.BannerLinkTextOWSTEXT = result.BannerLinkTextOWST" +
                    "EXT;\r\n                        if(typeof me.ButtonMaxCharacters != \'undefined\' &&" +
                    " me.ButtonMaxCharacters > 0) {\r\n                            if(resultJson.Banner" +
                    "LinkTextOWSTEXT !=null)\r\n                                resultJson.BannerLinkTe" +
                    "xtOWSTEXT = resultJson.BannerLinkTextOWSTEXT.substring(0, me.ButtonMaxCharacters" +
                    ");\r\n                        }\r\n                        resultJson.BannerSubHeadi" +
                    "ngOWSTEXT = result.BannerSubHeadingOWSTEXT;\r\n                        if(typeof m" +
                    "e.H2MaxCharacters != \'undefined\' && me.H2MaxCharacters > 0) {\r\n                 " +
                    "           if(resultJson.BannerSubHeadingOWSTEXT !=null)\r\n                      " +
                    "          resultJson.BannerSubHeadingOWSTEXT = resultJson.BannerSubHeadingOWSTEX" +
                    "T.substring(0, me.H2MaxCharacters);\r\n                        }\r\n                " +
                    "        resultJson.BannerLinkUrlOWSURLH = result.BannerLinkUrlOWSURLH;\r\n        " +
                    "                var href = new String(resultJson.BannerLinkUrlOWSURLH);\r\n       " +
                    "                 if (href.indexOf(\",\") > -1) {\r\n                            href" +
                    " = href.substring(0, href.indexOf(\",\"));\r\n                        }\r\n           " +
                    "             resultJson.BannerLinkUrlOWSURLH = href;\r\n\r\n                        " +
                    "if (typeof me.linkButtonTheme != \"undefined\") resultJson.LinkButtonTheme = me.li" +
                    "nkButtonTheme;\r\n                        else resultJson.LinkButtonTheme = \" \";\r\n" +
                    "                        if (typeof me.linkButtonTextTheme != \"undefined\") result" +
                    "Json.LinkButtonTextTheme = me.linkButtonTextTheme;\r\n                        else" +
                    " resultJson.LinkButtonTextTheme = \" \";\r\n                        var li = liTempl" +
                    "ate;\r\n                        li = Mustache.to_html(liTemplate, resultJson);\r\n  " +
                    "                      $(\".ia-banner-slides\", me.targetDiv).append(li);\r\n        " +
                    "                if(typeof me.TextLocation != \'undefined\') {\r\n                   " +
                    "         $(\".ia-banner-content\", me.targetDiv).addClass(me.TextLocation);\r\n     " +
                    "                   }\r\n                        if(typeof me.TextColorTheme != \'un" +
                    "defined\') {\r\n                            $(\".ia-banner-content\", me.targetDiv).a" +
                    "ddClass(me.TextColorTheme);\r\n                        }\r\n                        " +
                    "if(typeof me.TextAlignment != \'undefined\') {\r\n                            $(\".ia" +
                    "-banner-content\", me.targetDiv).addClass(me.TextAlignment);\r\n                   " +
                    "     }\r\n                    });\r\n                    if($(\'.ia-banner-item\').len" +
                    "gth <2)\r\n                    {\r\n                        me.autoPlay = false;\r\n  " +
                    "                      me.showNavigator= false;                        \r\n        " +
                    "            }\r\n\r\n                    $(\".ia-banner-slides\", me.targetDiv).owlCar" +
                    "ousel({\r\n                        autoplayHoverPause: false, // pause on mouse ho" +
                    "ver\r\n                        smartSpeed: 500, // slide transition speed  \t\r\n    " +
                    "                    dotsEach: true, // show a dot for each slide item\r\n         " +
                    "               navContainer: \".ia-banner-nav\",\r\n                        dotsCont" +
                    "ainer: \".ia-banner-dots\",\r\n                        navText: [\"<span class=\\\"ia-b" +
                    "anner-prev fa fa-chevron-left\\\"></span>\", \"<span class=\\\"ia-banner-next fa fa-ch" +
                    "evron-right\\\"></span>\"],\r\n                        items: 1, // Number of items t" +
                    "o show on screen\r\n                        autoplaySpeed: 500, // slide transitio" +
                    "n speed when autoplay = true\r\n                        mouseDrag: ($(\'.ia-banner-" +
                    "item\').length <2 ? false : true),\r\n                        singleItem: ($(\'.ia-b" +
                    "anner-item\').length <2 ? true : false),\r\n                        //Values to be " +
                    "set by InterAction Banner Instruction Set:\r\n                        loop: (typeo" +
                    "f me.infiniteLoop != \"undefined\" ? me.infiniteLoop : false), // Inifnity loop. D" +
                    "uplicate last and first items to get loop illusion\r\n                        auto" +
                    "play: (typeof me.autoPlay != \"undefined\" ? me.autoPlay : false), // start slider" +
                    " rotation on page load\r\n                        autoplayTimeout: (typeof me.slid" +
                    "eDuration != \"undefined\" ? me.slideDuration : 5000), // slide duration when auto" +
                    "play = true\r\n                        nav: me.showNavigator, // show prev and nex" +
                    "t links\r\n                        dots: me.showNavigator, // show dot navigation\r" +
                    "\n                        //For Fade transition, the following two must be set. F" +
                    "or slide, neither should be set                        \r\n                       " +
                    " animateOut: (typeof me.transitionEffect != \"undefined\" ? (me.transitionEffect.t" +
                    "oLowerCase() == \"fade\" ? \"fadeOut\" : me.transitionEffect.toLowerCase() ==\"vertic" +
                    "al\" ? \"owl-goDown-out\" : false) : false),\r\n                        animateIn: (t" +
                    "ypeof me.transitionEffect != \"undefined\" ? (me.transitionEffect.toLowerCase() ==" +
                    " \"fade\" ? \"fadeIn\" :  me.transitionEffect.toLowerCase() ==\"vertical\" ? \"owl-goDo" +
                    "wn-in\" : false) : false),\r\n  \t\r\n                    });\r\n                    if(" +
                    "me.autoPlay != false){\r\n                        var owl = $(\'.ia-banner-slides\')" +
                    ";\r\n                        $(\'.ia-banner-play-control\').click(function(){\n      " +
                    "                      owl.trigger(\'play.owl.autoplay\',[1000]);\n                 " +
                    "       });\n                        $(\'.ia-banner-pause-control\').click(function(" +
                    "){\n                            owl.trigger(\'stop.owl.autoplay\');\n               " +
                    "         });\r\n                    }\r\n                    else\r\n                 " +
                    "   {\r\n                        $(\'.ia-banner-pause\').hide();\r\n                   " +
                    " }\r\n\r\n                    $(\'.ia-banner-content span:empty\').parent().hide();\r\n " +
                    "               }\r\n            };\r\n          \r\n        };\r\n    }\r\n\r\n    \r\n       " +
                    "     \r\n\r\n    \r\n        $.ajaxSetup({\r\n            cache: true\r\n        });\r\n\r\n  " +
                    "      var thisBanner = new Akumina.InterAction.Banner();\r\n        thisBanner.uni" +
                    "queId = \'");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\';\r\n        thisBanner.targetDiv = \"#div\" + thisBanner.uniqueId;\r\n        thisBan" +
                    "ner.itemsResult = ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write(";\r\n        thisBanner.templateJson = ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write(";\r\n        ");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write(@"
        $(thisBanner.targetDiv).addClass(thisBanner.webPartTheme);                                                    
        $.getScript(bannerResourcePathValue + ""/js/vendor/owl.carousel.min.js"", function() { 
            thisBanner.getSearchResultsUsingREST(thisBanner);
        });               
    
</script>

");
            parameterContainer.Controls[7].RenderControl(@__w);
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
