//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Akumina.WebParts.SiteLinks.SiteLinks {
    public partial class SiteLinks {
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected Literal litTop;
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected Literal litDivID;
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected Literal uxUniqueId1;
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected Literal uxUniqueId2;
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected Literal litUniqueId;
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected Literal uxUniqueId3;
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected Literal uxUniqueId6;
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected Literal uxUniqueId4;
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected Literal litTemplates;
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected Literal litProperties;
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected Literal uxUniqueId5;
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected Literal uxUniqueId7;
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator TemplateControl(SiteLinks target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private Literal @__BuildControllitTop() {
            Literal @__ctrl;
            @__ctrl = new Literal();
            this.litTop = @__ctrl;
            @__ctrl.ID = "litTop";
            return @__ctrl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private Literal @__BuildControllitDivID() {
            Literal @__ctrl;
            @__ctrl = new Literal();
            this.litDivID = @__ctrl;
            @__ctrl.ID = "litDivID";
            return @__ctrl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private Literal @__BuildControluxUniqueId1() {
            Literal @__ctrl;
            @__ctrl = new Literal();
            this.uxUniqueId1 = @__ctrl;
            @__ctrl.ID = "uxUniqueId1";
            return @__ctrl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private Literal @__BuildControluxUniqueId2() {
            Literal @__ctrl;
            @__ctrl = new Literal();
            this.uxUniqueId2 = @__ctrl;
            @__ctrl.ID = "uxUniqueId2";
            return @__ctrl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private Literal @__BuildControllitUniqueId() {
            Literal @__ctrl;
            @__ctrl = new Literal();
            this.litUniqueId = @__ctrl;
            @__ctrl.ID = "litUniqueId";
            return @__ctrl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private Literal @__BuildControluxUniqueId3() {
            Literal @__ctrl;
            @__ctrl = new Literal();
            this.uxUniqueId3 = @__ctrl;
            @__ctrl.ID = "uxUniqueId3";
            return @__ctrl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private Literal @__BuildControluxUniqueId6() {
            Literal @__ctrl;
            @__ctrl = new Literal();
            this.uxUniqueId6 = @__ctrl;
            @__ctrl.ID = "uxUniqueId6";
            return @__ctrl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private Literal @__BuildControluxUniqueId4() {
            Literal @__ctrl;
            @__ctrl = new Literal();
            this.uxUniqueId4 = @__ctrl;
            @__ctrl.ID = "uxUniqueId4";
            return @__ctrl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private Literal @__BuildControllitTemplates() {
            Literal @__ctrl;
            @__ctrl = new Literal();
            this.litTemplates = @__ctrl;
            @__ctrl.ID = "litTemplates";
            return @__ctrl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private Literal @__BuildControllitProperties() {
            Literal @__ctrl;
            @__ctrl = new Literal();
            this.litProperties = @__ctrl;
            @__ctrl.ID = "litProperties";
            return @__ctrl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private Literal @__BuildControluxUniqueId5() {
            Literal @__ctrl;
            @__ctrl = new Literal();
            this.uxUniqueId5 = @__ctrl;
            @__ctrl.ID = "uxUniqueId5";
            return @__ctrl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private Literal @__BuildControluxUniqueId7() {
            Literal @__ctrl;
            @__ctrl = new Literal();
            this.uxUniqueId7 = @__ctrl;
            @__ctrl.ID = "uxUniqueId7";
            return @__ctrl;
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(SiteLinks @__ctrl) {
            Literal @__ctrl1;
            @__ctrl1 = this.@__BuildControllitTop();
            IParserAccessor @__parser = ((IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new LiteralControl("\r\n\r\n<div id=\"div"));
            Literal @__ctrl2;
            @__ctrl2 = this.@__BuildControllitDivID();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new LiteralControl("\" class=\"interAction\">\r\n    \r\n</div>\r\n\r\n<script type=\"text/javascript\">\r\n    $(do" +
                        "cument).ready(function() {\r\n        $.ajaxSetup({\r\n            cache: true\r\n    " +
                        "    });\r\n\r\n        var thisSiteLinks"));
            Literal @__ctrl3;
            @__ctrl3 = this.@__BuildControluxUniqueId1();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new LiteralControl(" = new Akumina.InterAction.SiteLinks();\r\n        thisSiteLinks"));
            Literal @__ctrl4;
            @__ctrl4 = this.@__BuildControluxUniqueId2();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new LiteralControl(".uniqueId = \'"));
            Literal @__ctrl5;
            @__ctrl5 = this.@__BuildControllitUniqueId();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new LiteralControl("\';\r\n        thisSiteLinks"));
            Literal @__ctrl6;
            @__ctrl6 = this.@__BuildControluxUniqueId3();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new LiteralControl(".targetDiv = \"#div\" + thisSiteLinks"));
            Literal @__ctrl7;
            @__ctrl7 = this.@__BuildControluxUniqueId6();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new LiteralControl(".uniqueId;\r\n        thisSiteLinks"));
            Literal @__ctrl8;
            @__ctrl8 = this.@__BuildControluxUniqueId4();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new LiteralControl(".templateJson = "));
            Literal @__ctrl9;
            @__ctrl9 = this.@__BuildControllitTemplates();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new LiteralControl(";\r\n        \r\n        "));
            Literal @__ctrl10;
            @__ctrl10 = this.@__BuildControllitProperties();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new LiteralControl("\r\n\r\n        thisSiteLinks"));
            Literal @__ctrl11;
            @__ctrl11 = this.@__BuildControluxUniqueId5();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new LiteralControl(".getDataUsingREST(thisSiteLinks"));
            Literal @__ctrl12;
            @__ctrl12 = this.@__BuildControluxUniqueId7();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new LiteralControl(");\r\n    });    \r\n</script>\r\n"));
        }
        
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new EventHandler(this.Page_Load);
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [GeneratedCode("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
