//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akumina.ListDefinition.Provision.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Akumina.ListDefinition.Provision.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Term Set Name&quot;,&quot;Term Set Description&quot;,&quot;LCID&quot;,&quot;Available for Tagging&quot;,&quot;Term Description&quot;,&quot;Level 1 Term&quot;,&quot;Level 2 Term&quot;,&quot;Level 3 Term&quot;,&quot;Level 4 Term&quot;,&quot;Level 5 Term&quot;,&quot;Level 6 Term&quot;,&quot;Level 7 Term&quot;
        ///&quot;Category&quot;,&quot;Enterprise taxonomy for companies by industry&quot;,,&quot;True&quot;,,&quot;IT&quot;,,,,,,
        ///,,,&quot;True&quot;,,&quot;Akumina Discussions&quot;,&quot;Discussions1&quot;,,,,,
        ///,,,&quot;True&quot;,,&quot;Akumina Discussions&quot;,&quot;Discussions2&quot;,,,,,
        ///,,,&quot;True&quot;,,&quot;Akumina Discussions&quot;,&quot;Discussions3&quot;,,,,,
        ///,,,&quot;True&quot;,,&quot;Akumina Discussions&quot;,&quot;Discussions4&quot;,,,,,
        ///,,,&quot;True&quot;,,&quot;Akumina A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AkuminaTaxonomy {
            get {
                return ResourceManager.GetString("AkuminaTaxonomy", resourceCulture);
            }
        }
    }
}
