//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Akumina.WebParts.DocumentsSandbox.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Akumina.WebParts.DocumentsSandbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string _cloneColumns {
            get {
                return ResourceManager.GetString("_cloneColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All documents, files, and folders in .
        /// </summary>
        public static string breadCrumpText {
            get {
                return ResourceManager.GetString("breadCrumpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string btnCheckIn {
            get {
                return ResourceManager.GetString("btnCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string btnCheckInMore {
            get {
                return ResourceManager.GetString("btnCheckInMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string btnCheckOut {
            get {
                return ResourceManager.GetString("btnCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string btnCheckOutAll {
            get {
                return ResourceManager.GetString("btnCheckOutAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance Details.
        /// </summary>
        public static string btnCompliance {
            get {
                return ResourceManager.GetString("btnCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard checkout.
        /// </summary>
        public static string btnDiscardCheckOut {
            get {
                return ResourceManager.GetString("btnDiscardCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard checkout.
        /// </summary>
        public static string btnDiscardChkOutAll {
            get {
                return ResourceManager.GetString("btnDiscardChkOutAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string btnDoc {
            get {
                return ResourceManager.GetString("btnDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string btnDownload {
            get {
                return ResourceManager.GetString("btnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit properties.
        /// </summary>
        public static string btnEditProperties {
            get {
                return ResourceManager.GetString("btnEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string btnExcelDoc {
            get {
                return ResourceManager.GetString("btnExcelDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow this File.
        /// </summary>
        public static string btnFollow {
            get {
                return ResourceManager.GetString("btnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string btnMore {
            get {
                return ResourceManager.GetString("btnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote.
        /// </summary>
        public static string btnONoteDoc {
            get {
                return ResourceManager.GetString("btnONoteDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string btnOpen {
            get {
                return ResourceManager.GetString("btnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint.
        /// </summary>
        public static string btnPPTDoc {
            get {
                return ResourceManager.GetString("btnPPTDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this File...
        /// </summary>
        public static string btnShare {
            get {
                return ResourceManager.GetString("btnShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is shared With...
        /// </summary>
        public static string btnShareWith {
            get {
                return ResourceManager.GetString("btnShareWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string btnUpload {
            get {
                return ResourceManager.GetString("btnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View properties.
        /// </summary>
        public static string btnViewProperties {
            get {
                return ResourceManager.GetString("btnViewProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string btnWordDoc {
            get {
                return ResourceManager.GetString("btnWordDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows.
        /// </summary>
        public static string btnWorkflow {
            get {
                return ResourceManager.GetString("btnWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /css/ia-interaction-controls.css|/css/ia-document-grid.css.
        /// </summary>
        public static string CSS_Links {
            get {
                return ResourceManager.GetString("CSS_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script id=&quot;dms_template&quot; type=&quot;text/html&quot;&gt;
        ///   
        ///        &lt;table id=&quot;ogrid&quot; class=&quot;ia-document-library-list tablesaw tablesaw-stack fixed_headers&quot; cellspacing=&quot;0&quot; rules=&quot;all&quot; data-mode=&quot;stack&quot; border=&quot;1&quot; id=&quot;ogrid&quot; style=&quot;border-collapse: collapse;&quot;&gt;
        ///            &lt;thead&gt;
        ///                &lt;tr class=&quot;sticky&quot;&gt;
        ///                    &lt;th class=&quot;ia-doclib-header-checkbox&quot; scope=&quot;col&quot;&gt;
        ///                        &lt;input type=&quot;checkbox&quot; class=&quot;ia-doclist-selectAll&quot; onchange=&quot;selectall(this.checked);&quot;&gt;&lt;/th&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DMSTemplate {
            get {
                return ResourceManager.GetString("DMSTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Your Search returned no results!.
        /// </summary>
        public static string Gird_EmptyDataText {
            get {
                return ResourceManager.GetString("Gird_EmptyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |TypeUrl|LinkFilename|Modified|Editor|ID|File_x0020_Type|Path|Status|EditorClone|ModifiedTime|EditPermission.
        /// </summary>
        public static string Grid_Columns {
            get {
                return ResourceManager.GetString("Grid_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name,Modified,Modified By.
        /// </summary>
        public static string Grid_Header_ColumnNames {
            get {
                return ResourceManager.GetString("Grid_Header_ColumnNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /js/vendor/jquery-2.1.3.min.js.
        /// </summary>
        public static string JquerylibraryPath {
            get {
                return ResourceManager.GetString("JquerylibraryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /js/vendor/mustache.min.js|/js/vendor/modernizr.js|/js/controls/ia-document-grid-sandbox.js|/js/controls/ia-context-menu-sandbox.js|/js/vendor/quicksearch.js|/js/controls/ia-document-list-sandbox.js|/js/vendor/jquery.dropdown.js|/js/vendor/jquery.magnific-popup.js|/js/components/modal.js|/js/vendor/jstree.js|/js/controls/ia-drag-drop-sandbox.js|/js/components/accordion.js|/js/vendor/picker.js|/js/vendor/picker.date.js|/js/vendor/tablesaw.stackonly.js|/js/controls/ia-tabs-sandbox.js.
        /// </summary>
        public static string JS_Links {
            get {
                return ResourceManager.GetString("JS_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string MetaField {
            get {
                return ResourceManager.GetString("MetaField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor|File_x0020_Type|Category.
        /// </summary>
        public static string Refiner_Fields {
            get {
                return ResourceManager.GetString("Refiner_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Folder|Include SubFolders.
        /// </summary>
        public static string SearchDropDwonOptions {
            get {
                return ResourceManager.GetString("SearchDropDwonOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string Tab_AllFiles_Text {
            get {
                return ResourceManager.GetString("Tab_AllFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Files.
        /// </summary>
        public static string Tab_MyFiles_Text {
            get {
                return ResourceManager.GetString("Tab_MyFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Tab_RecentFiles_Text {
            get {
                return ResourceManager.GetString("Tab_RecentFiles_Text", resourceCulture);
            }
        }
    }
}
