//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akumina.WebParts.Banner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Akumina.WebParts.Banner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;interAction&quot;&gt;
        ///    &lt;div class=&quot;ia-banner&quot;&gt;
        ///        &lt;div class=&quot;owl-carousel ia-banner-slides&quot;&gt;&lt;/div&gt;
        ///        &lt;div class=&quot;ia-banner-nav&quot;&gt;&lt;/div&gt;
        ///        &lt;div class=&quot;ia-banner-dots&quot;&gt;&lt;/div&gt;
        ///        &lt;div class=&quot;ia-banner-pause&quot;&gt;
        ///            &lt;span class=&quot;ia-banner-pause-control fa fa-pause&quot;&gt;&lt;/span&gt;
        ///            &lt;span class=&quot;ia-banner-play-control fa fa-play&quot;&gt;&lt;/span&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string ControlTemplate {
            get {
                return ResourceManager.GetString("ControlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;ia-banner-item&quot;&gt; 
        ///	&lt;img class=&quot;ia-banner-img&quot; src=&quot;{{BannerImageOWSURLH}}&quot; alt=&quot;{{BannerImageAltTextOWSTEXT}}&quot; /&gt; 
        ///	&lt;div class=&quot;ia-banner-content&quot;&gt;
        ///		&lt;h1 class=&quot;ia-banner-title&quot;&gt;{{BannerHeadingOWSTEXT}}&lt;/h1&gt;
        ///		&lt;h2 class=&quot;ia-banner-subtitle&quot;&gt;{{BannerSubHeadingOWSTEXT}}&lt;/h2&gt;
        ///		&lt;a href=&quot;{{BannerLinkUrlOWSURLH}}&quot; class=&quot;ia-button {{LinkButtonTheme}}&quot; title=&quot;{{BannerLinkHoverTextOWSTEXT}}&quot; target=&quot;{{BannerLinkTargetOWSCHCS}}&quot;&gt;
        ///            &lt;span class=&quot;{{LinkButtonTextTheme}}&quot;&gt;{{BannerLinkTextOW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemTemplate {
            get {
                return ResourceManager.GetString("ItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Play:.
        /// </summary>
        internal static string lbl_AutoPlay {
            get {
                return ResourceManager.GetString("lbl_AutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Theme:.
        /// </summary>
        internal static string lbl_BannerTheme {
            get {
                return ResourceManager.GetString("lbl_BannerTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite Loop:.
        /// </summary>
        internal static string lbl_InfinitLoop {
            get {
                return ResourceManager.GetString("lbl_InfinitLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction Set:.
        /// </summary>
        internal static string lbl_InstructionSet {
            get {
                return ResourceManager.GetString("lbl_InstructionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Button Theme:.
        /// </summary>
        internal static string lbl_LinkButtonTheme {
            get {
                return ResourceManager.GetString("lbl_LinkButtonTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Text Theme:.
        /// </summary>
        internal static string lbl_LinkTextTheme {
            get {
                return ResourceManager.GetString("lbl_LinkTextTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Style:.
        /// </summary>
        internal static string lbl_RenderStyle {
            get {
                return ResourceManager.GetString("lbl_RenderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Path:.
        /// </summary>
        internal static string lbl_ResourcePath {
            get {
                return ResourceManager.GetString("lbl_ResourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Source:.
        /// </summary>
        internal static string lbl_ResultSource {
            get {
                return ResourceManager.GetString("lbl_ResultSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Level:.
        /// </summary>
        internal static string lbl_SearchLevel {
            get {
                return ResourceManager.GetString("lbl_SearchLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Navigator:.
        /// </summary>
        internal static string lbl_ShowNavigator {
            get {
                return ResourceManager.GetString("lbl_ShowNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Duration:.
        /// </summary>
        internal static string lbl_SlideDuration {
            get {
                return ResourceManager.GetString("lbl_SlideDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition:.
        /// </summary>
        internal static string lbl_Transition {
            get {
                return ResourceManager.GetString("lbl_Transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /js/vendor/jquery-2.1.3.min.js|/js/vendor/owl.carousel.min.js|/js/vendor/mustache.min.js.
        /// </summary>
        internal static string pdl_JSFiles {
            get {
                return ResourceManager.GetString("pdl_JSFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Collection~SPSiteSubscription|Web~SPWeb|Search Application~Ssa.
        /// </summary>
        internal static string pdl_ResourceLevels {
            get {
                return ResourceManager.GetString("pdl_ResourceLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /css/ia-interaction-controls.css|/css/owl.transitions.css|/css/owl.carousel.css|/css/putnam-tiles.css.
        /// </summary>
        internal static string pdl_StyleSheets {
            get {
                return ResourceManager.GetString("pdl_StyleSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide~slide|Fade~fade.
        /// </summary>
        internal static string pdl_Transistions {
            get {
                return ResourceManager.GetString("pdl_Transistions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;interAction&quot;&gt;
        ///    &lt;div class=&quot;ia-banner&quot;&gt;
        ///        &lt;div class=&quot;tiles-wrap&quot;&gt;
        ///		{{#Items}}
        ///				&lt;div class=&quot;{{tileClass}}&quot;&gt;
        ///					&lt;div class=&quot;ia-banner-item&quot;&gt;
        ///					    &lt;a href=&quot;{{BannerLinkUrlOWSURLH}}&quot; class=&quot;tile-link&quot; title=&quot;{{BannerLinkHoverTextOWSTEXT}}&quot; target=&quot;{{BannerLinkTargetOWSCHCS}}&quot; style=&quot;background-image:url({{BannerImageOWSURLH}})&quot;&gt;
        ///						    &lt;div class=&quot;ia-banner-content&quot;&gt;
        ///							    &lt;h1 class=&quot;ia-banner-title&quot;&gt;{{BannerHeadingOWSTEXT}}&lt;/h1&gt;
        ///							    &lt;h2 class=&quot;ia-banner-su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TileItemTemplate {
            get {
                return ResourceManager.GetString("TileItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_layouts/15/.
        /// </summary>
        internal static string val_ScriptBase {
            get {
                return ResourceManager.GetString("val_ScriptBase", resourceCulture);
            }
        }
    }
}
