//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akumina.WebParts.Documents.DocumentTab {
    using System.Linq;
    using System.Web.Security;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;
    using System.Web.UI.WebControls;
    using System.Xml.Linq;
    using System.Web.UI;
    using System.Web.UI.HtmlControls;
    using System.Web;
    using System.Configuration;
    using System;
    using System.Text;
    using System.Web.Profile;
    using System.Web.Caching;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.WebControls.Expressions;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    using System.Web.DynamicData;
    
    
    public partial class DocumentTab {
        
        protected global::System.Web.UI.WebControls.HiddenField lblID;
        
        protected global::System.Web.UI.HtmlControls.HtmlAnchor allFiles;
        
        protected global::System.Web.UI.HtmlControls.HtmlAnchor myFiles;
        
        protected global::System.Web.UI.HtmlControls.HtmlAnchor popularFiles;
        
        protected global::System.Web.UI.HtmlControls.HtmlAnchor recentFiles;
        
        protected global::System.Web.UI.UpdatePanel updatePnlTab;
        
        public static implicit operator global::System.Web.UI.TemplateControl(DocumentTab target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControllblID() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.lblID = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "lblID";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControlallFiles() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
            this.allFiles = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "allFiles";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "allFiles");
            @__ctrl.Title = "All Files";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onclick", "tabHighlight(\'0\',this) ");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("All Files\r\n                           <span class=\"ia-tab-count allfilecount\"></s" +
                        "pan>\r\n\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControlmyFiles() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
            this.myFiles = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "myFiles";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "myFiles");
            @__ctrl.Title = "My Files";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onclick", " tabHighlight(\'1\',this)");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("My Files\r\n                            <span class=\"ia-tab-count myfilecount\"></sp" +
                        "an>\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControlpopularFiles() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
            this.popularFiles = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "popularFiles";
            @__ctrl.Title = "Popular";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "popularFiles");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onclick", "tabHighlight(\'2\',this)");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Popular\r\n                          <span class=\"ia-tab-count popularfilecount\"></" +
                        "span>   \r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControlrecentFiles() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
            this.recentFiles = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "recentFiles";
            @__ctrl.Title = "Recent";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "recentFiles");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("onclick", " tabHighlight(\'3\',this)");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Recent\r\n                            <span class=\"ia-tab-count recentfilecount\"></" +
                        "span>\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl1;
            @__ctrl1 = this.@__BuildControllblID();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            <div class=\"ia-tabs\">\r\n                <ul class=\"ia-tabs-nav\">\r\n  " +
                        "                  <li>\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl2;
            @__ctrl2 = this.@__BuildControlallFiles();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </li>\r\n                    <li>\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl3;
            @__ctrl3 = this.@__BuildControlmyFiles();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </li>\r\n                    <li>\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl4;
            @__ctrl4 = this.@__BuildControlpopularFiles();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </li>\r\n                    <li>\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl5;
            @__ctrl5 = this.@__BuildControlrecentFiles();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </li>\r\n                </ul>\r\n                \r\n           " +
                        "     \r\n            </div>\r\n        "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.UpdatePanel @__BuildControlupdatePnlTab() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            this.updatePnlTab = @__ctrl;
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            @__ctrl.ID = "updatePnlTab";
            @__ctrl.UpdateMode = global::System.Web.UI.UpdatePanelUpdateMode.Conditional;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Akumina.WebParts.Documents.DocumentTab.DocumentTab @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<div class=\"interAction\">\r\n    "));
            global::System.Web.UI.UpdatePanel @__ctrl1;
            @__ctrl1 = this.@__BuildControlupdatePnlTab();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</div>\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
