//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akumina.WebParts.Announcement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Akumina.WebParts.Announcement.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /css/ia-interaction-controls.css.
        /// </summary>
        internal static string CssDetail {
            get {
                return ResourceManager.GetString("CssDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /css/ia-interaction-controls.css.
        /// </summary>
        internal static string CssItems {
            get {
                return ResourceManager.GetString("CssItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;rog-column&quot;&gt;
        ///&lt;h1 class=&quot;rog-page-title&quot;&gt;{{Title}}&lt;/h1&gt;
        ///&lt;section class=&quot;rog-announcement-detail&quot;&gt;
        ///    {{{Body}}} {{{Photo}}}
        ///&lt;/section&gt;
        ///
        ///&lt;div class=&quot;meta-data&quot; hidden&gt;
        ///    &lt;div class=&quot;seo-title&quot;&gt;{{SEOTitle}}&lt;/div&gt;
        ///    &lt;div class=&quot;seo-description&quot;&gt;{{SEODescription}}&lt;/div&gt;
        ///    &lt;div class=&quot;seo-keywords&quot;&gt;{{SEOKeywords}}&lt;/div&gt;
        ///&lt;/div&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string ItemDetailTemplate {
            get {
                return ResourceManager.GetString("ItemDetailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;section class=&quot;rog-widget rog-widget-announcements&quot;&gt;
        ///    &lt;div class=&quot;rog-widget-header&quot;&gt;
        ///        &lt;h3&gt;&lt;span class=&quot;fa fa-rss&quot;&gt;&lt;/span&gt; {{WebPartTitle}}&lt;/h3&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;rog-widget-content&quot;&gt;
        ///        &lt;div class=&quot;interAction&quot;&gt;
        ///            &lt;div class=&quot;ia-announcements&quot;&gt;
        ///                &lt;ul&gt;
        ///                    {{#items}}
        ///                    &lt;li&gt;
        ///                        &lt;h4 class=&quot;ia-announcement-title&quot;&gt;&lt;a href=&quot;{{Url}}&quot;&gt;{{Title}}&lt;/a&gt;&lt;/h4&gt;
        ///                        &lt;p class=&quot;ia-annoucement [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemListTemplate {
            get {
                return ResourceManager.GetString("ItemListTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /js/vendor/jquery-2.1.3.min.js|/js/vendor/mustache.min.js.
        /// </summary>
        internal static string JsLibrary {
            get {
                return ResourceManager.GetString("JsLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 class=&quot;rog-page-title&quot;&gt;{{WebPartTitle}}&lt;/h1&gt;
        ///&lt;section class=&quot;rog-widget rog-widget-announcements&quot;&gt;
        ///    &lt;div class=&quot;rog-widget-content&quot;&gt;
        ///        &lt;div class=&quot;interAction&quot;&gt;
        ///            &lt;div class=&quot;ia-announcements&quot;&gt;
        ///                &lt;ul&gt;
        ///                    {{#items}}
        ///                    &lt;li&gt;
        ///                        &lt;h4 class=&quot;ia-announcement-title&quot;&gt;&lt;a href=&quot;{{Url}}&quot;&gt;{{Title}}&lt;/a&gt;&lt;/h4&gt;
        ///                        &lt;p class=&quot;ia-announcement-summary&quot;&gt;&lt;strong&gt;{{{Created}}}&lt;/strong&gt; {{{Summary}}}...&lt;/p&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PageItemListTemplate {
            get {
                return ResourceManager.GetString("PageItemListTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akumina InterAction.
        /// </summary>
        internal static string PropertyGroup {
            get {
                return ResourceManager.GetString("PropertyGroup", resourceCulture);
            }
        }
    }
}
