//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akumina.WebParts.DocumentSummaryList.DocumentSummaryList {
    using System.Linq;
    using System.Web.Security;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;
    using System.Web.UI.WebControls;
    using System.Xml.Linq;
    using System.Web.UI;
    using System;
    using System.Web.UI.HtmlControls;
    using System.Web;
    using System.Configuration;
    using System.ComponentModel.DataAnnotations;
    using System.Text;
    using System.Web.Profile;
    using System.Web.Caching;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.WebControls.Expressions;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    using System.Web.DynamicData;
    using System.CodeDom.Compiler;
    
    
    public partial class DocumentSummaryList {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litTop;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox controlDslHtml;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox itemDslHtml;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litDSL_Title;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litDSL_Icon;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litDSL_ShowHeader;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litTemplates;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litResultNew;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litResultRecent;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litResultPopular;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litResultRecommended;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litTabNames;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal NewTabDescription;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal NewTabCount;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal RecentTabDescription;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal RecentTabCount;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal PopularTabDescription;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal PopularTabCount;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal RecommendedTabDescription;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal RecommendedTabCount;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litCurrentSite;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(DocumentSummaryList target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitTop() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litTop = @__ctrl;
            @__ctrl.ID = "litTop";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlcontrolDslHtml() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.controlDslHtml = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "controlDslHtml";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display:none");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlitemDslHtml() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.itemDslHtml = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "itemDslHtml";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display:none");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitDSL_Title() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litDSL_Title = @__ctrl;
            @__ctrl.ID = "litDSL_Title";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitDSL_Icon() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litDSL_Icon = @__ctrl;
            @__ctrl.ID = "litDSL_Icon";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitDSL_ShowHeader() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litDSL_ShowHeader = @__ctrl;
            @__ctrl.ID = "litDSL_ShowHeader";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitTemplates() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litTemplates = @__ctrl;
            @__ctrl.ID = "litTemplates";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitResultNew() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litResultNew = @__ctrl;
            @__ctrl.ID = "litResultNew";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitResultRecent() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litResultRecent = @__ctrl;
            @__ctrl.ID = "litResultRecent";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitResultPopular() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litResultPopular = @__ctrl;
            @__ctrl.ID = "litResultPopular";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitResultRecommended() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litResultRecommended = @__ctrl;
            @__ctrl.ID = "litResultRecommended";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitTabNames() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litTabNames = @__ctrl;
            @__ctrl.ID = "litTabNames";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlNewTabDescription() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.NewTabDescription = @__ctrl;
            @__ctrl.ID = "NewTabDescription";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlNewTabCount() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.NewTabCount = @__ctrl;
            @__ctrl.ID = "NewTabCount";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlRecentTabDescription() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.RecentTabDescription = @__ctrl;
            @__ctrl.ID = "RecentTabDescription";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlRecentTabCount() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.RecentTabCount = @__ctrl;
            @__ctrl.ID = "RecentTabCount";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlPopularTabDescription() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.PopularTabDescription = @__ctrl;
            @__ctrl.ID = "PopularTabDescription";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlPopularTabCount() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.PopularTabCount = @__ctrl;
            @__ctrl.ID = "PopularTabCount";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlRecommendedTabDescription() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.RecommendedTabDescription = @__ctrl;
            @__ctrl.ID = "RecommendedTabDescription";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlRecommendedTabCount() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.RecommendedTabCount = @__ctrl;
            @__ctrl.ID = "RecommendedTabCount";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitCurrentSite() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litCurrentSite = @__ctrl;
            @__ctrl.ID = "litCurrentSite";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::Akumina.WebParts.DocumentSummaryList.DocumentSummaryList.DocumentSummaryList @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<script type=\"text/javascript\">\r\n    if (Akumina === undefined) {\r\n        var " +
                        "Akumina = {};\r\n    }\r\n    if (Akumina.InterAction === undefined) {\r\n        Akum" +
                        "ina.InterAction = {};\r\n    }\r\n</script>\r\n\r\n"));
            global::System.Web.UI.WebControls.Literal @__ctrl1;
            @__ctrl1 = this.@__BuildControllitTop();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            @__ctrl2 = this.@__BuildControlcontrolDslHtml();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            @__ctrl3 = this.@__BuildControlitemDslHtml();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n<div id=\"targetDSL\"></div>\r\n<div id=\"targetNew\"></div>\r\n\r\n<script type=\"tex" +
                        "t/javascript\">\r\n\r\n    if (typeof jQuery == \'undefined\') {\r\n        document.writ" +
                        "e(\"<script type=\'text/javascript\' src=\'http://code.jquery.com/jquery-2.1.3.min.j" +
                        "s\'\" + \"/>\");\r\n    }\r\n</script>\r\n\r\n\r\n<script type=\"text/javascript\">\r\n    \r\n    i" +
                        "f (Akumina.InterAction.DSL === undefined) {\r\n      \r\n        Akumina.InterAction" +
                        ".DSL = function() {\r\n            this.targetDiv = \"#targetDSL\";\r\n            thi" +
                        "s.Url = \"\";\r\n            this.Name = \"\";\r\n            this.Date = \"\";\r\n         " +
                        "   \r\n            this.NewTabDescription = \"\";\r\n            this.NewTabCount= \"\";" +
                        "\r\n            this.RecentTabDescription = \"\";\r\n            this.RecentTabCount =" +
                        " \"\";\r\n            this.PopularTabDescription= \"\";\r\n            this.PopularTabCo" +
                        "unt = \"\";\r\n            this.RecommendedTabDescription = \"\";\r\n            this.Re" +
                        "commendedTabCount = \"\";\r\n            this.searchResults = {};\r\n            this." +
                        "templateJson = {}; \r\n            this.resultNew = {}; \r\n            this.resultR" +
                        "ecent = {}; \r\n            this.resultPopular = {}; \r\n            this.resultReco" +
                        "mmended = {}; \r\n            this.tabNames = {};             \r\n            \r\n    " +
                        "        \r\n            this.AddItemsToTab = function(tabName,items,tabCount,tabIn" +
                        "dex,liTemplate,me)\r\n            {\r\n\r\n                $.each(items, function(inde" +
                        "x, result) {\r\n                    var resultJson = {};\r\n                    resu" +
                        "ltJson.IconSrc = result.IconSrc;\r\n                    resultJson.FileUrl = resul" +
                        "t.FileUrl;\r\n                    resultJson.FileName = result.FileName;\r\n        " +
                        "            resultJson.SiteName = result.SiteName;\r\n                    resultJs" +
                        "on.Url = result.Url;\r\n\r\n                    var myDate =\"\";\r\n                   " +
                        " if(result.DateModified !=\"\"){\r\n                        myDate = new Date(result" +
                        ".DateModified);\r\n                        myDate = myDate.format(\"MM/dd/yyyy\");\r\n" +
                        "                    }\r\n                    resultJson.DateModified = myDate;\r\n  " +
                        "                  switch(tabName){\r\n                        case \"recent\":\r\n    " +
                        "                        resultJson.ModifiedBy = \"\";\r\n                           " +
                        " myDate = new Date(result.LogDateOcurred);\r\n                            myDate =" +
                        " myDate.format(\"MM/dd/yyyy\");\r\n                            resultJson.DateModifi" +
                        "ed = myDate;\r\n                            break;\r\n                        case \"" +
                        "popular\":\r\n                            resultJson.ModifiedBy = \"\";\r\n            " +
                        "                resultJson.DateModified = result.TotalLogs;\r\n                   " +
                        "         break;\r\n                        default:\r\n                            r" +
                        "esultJson.ModifiedBy = result.ModifiedBy;\r\n                            break;\r\n " +
                        "                   }                    \r\n                    if(tabName == \'pop" +
                        "ular\' && result.TotalLogs ==0){}\r\n                    else{\r\n                   " +
                        "     var li = liTemplate;\r\n                        li = Mustache.to_html(liTempl" +
                        "ate, resultJson);\r\n                        $(\".tab\" + tabIndex, me.targetDiv).ap" +
                        "pend(li);\r\n                    }\r\n                    \r\n                    if(t" +
                        "abCount > 0 && tabCount == (index+1)){\r\n                        return false;\r\n " +
                        "                   }\r\n                });\r\n            }\r\n\r\n            this.get" +
                        "SearchResultsUsingREST = function(me) {\r\n                var me = this;\r\n       " +
                        "         \r\n                var newTabIndex =-1;\r\n                var recentTabIn" +
                        "dex =-1;\r\n                var popularTabIndex =-1;\r\n                var recommen" +
                        "dedTabIndex =-1;\r\n\r\n\r\n               \r\n                var searchResultsHtml = \"" +
                        "\";\r\n                var DSLTemplate = $(\"#controlDslHtml\").val();//me.templateJs" +
                        "on.ControlTemplate;\r\n                var liTemplate =$(\"#itemDslHtml\").val(); //" +
                        "me.templateJson.ItemTemplate;\r\n                //Template\r\n                var r" +
                        "esultTemplateJson = {};\r\n                //Tabs Name\r\n                var newTab" +
                        "Description = this.NewTabDescription;\r\n                var recentTabDescription " +
                        "= this.RecentTabDescription;\r\n                var popularTabDescription = this.P" +
                        "opularTabDescription;\r\n                var recommendedTabDescription = this.Reco" +
                        "mmendedTabDescription;\r\n\r\n                resultTemplateJson[\"Title\"]  = \'"));
            global::System.Web.UI.WebControls.Literal @__ctrl4;
            @__ctrl4 = this.@__BuildControllitDSL_Title();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\';\r\n                resultTemplateJson[\"WebPartIcon\"]  =\'"));
            global::System.Web.UI.WebControls.Literal @__ctrl5;
            @__ctrl5 = this.@__BuildControllitDSL_Icon();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\';\r\n                resultTemplateJson[\"ShowHeader\"]  = "));
            global::System.Web.UI.WebControls.Literal @__ctrl6;
            @__ctrl6 = this.@__BuildControllitDSL_ShowHeader();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";\r\n                \r\n                $.each(me.tabNames, function(index, tab) {\r\n" +
                        "                    var field = \'tab\' + (index + 1) + \'_name\';\r\n                " +
                        "    var fieldDescription = \'tab\' + (index + 1) + \'_description\';\r\n              " +
                        "      var Column2Desc = \'tab\' + (index + 1) + \'_Column2Desc\';\r\n                 " +
                        "   var Column3Desc = \'tab\' + (index + 1) + \'_Column3Desc\';\r\n                    " +
                        "var Column4Desc = \'tab\' + (index + 1) + \'_Column4Desc\';\r\n                    res" +
                        "ultTemplateJson[field] = tab;\r\n                        \r\n                    swi" +
                        "tch(tab.toLowerCase().replace(\' \',\'\'))\r\n                    {\r\n                 " +
                        "       case \"newest\":\r\n                            newTabIndex= index +1;\r\n     " +
                        "                       resultTemplateJson[fieldDescription] = newTabDescription;" +
                        "\r\n                            resultTemplateJson[Column2Desc] = \"Site\";\r\n       " +
                        "                     resultTemplateJson[Column3Desc] = \"Modified Date\";\r\n       " +
                        "                     resultTemplateJson[Column4Desc] = \"Modified By\";\r\n         " +
                        "                   break;\r\n                        case \"myrecent\":\r\n           " +
                        "                 recentTabIndex= index +1;\r\n                            resultTe" +
                        "mplateJson[fieldDescription] =recentTabDescription; \r\n                          " +
                        "  resultTemplateJson[Column2Desc] = \"Site\";\r\n                            resultT" +
                        "emplateJson[Column3Desc] = \"Access Date\";\r\n                            resultTem" +
                        "plateJson[Column4Desc] = \"\";\r\n                            break;\r\n              " +
                        "          case \"popular\":\r\n                            popularTabIndex= index +1" +
                        ";\r\n                            resultTemplateJson[fieldDescription] = popularTab" +
                        "Description; \r\n                            resultTemplateJson[Column2Desc] = \"Si" +
                        "te\";\r\n                            resultTemplateJson[Column3Desc] = numberOfDays" +
                        "Popular >0 ? \"# Views Last \" + numberOfDaysPopular + \" days\" : \"# Views Last 30 " +
                        "days\";\r\n                            resultTemplateJson[Column4Desc] = \"\";\r\n     " +
                        "                       break;\r\n                        case \"recommended\":\r\n    " +
                        "                        recommendedTabIndex= index +1;\r\n                        " +
                        "    resultTemplateJson[fieldDescription]= recommendedTabDescription;\r\n          " +
                        "                  resultTemplateJson[Column2Desc] = \"Site\";\r\n                   " +
                        "         resultTemplateJson[Column3Desc] = \"Modified Date\";\r\n                   " +
                        "         resultTemplateJson[Column4Desc] = \"Modified By\";\r\n                     " +
                        "       break;\r\n\r\n                    }\r\n                });\r\n                   " +
                        "\r\n                   \r\n                DSLTemplate = Mustache.to_html(DSLTemplat" +
                        "e, resultTemplateJson);\r\n                    \r\n                $(me.targetDiv).a" +
                        "ppend(DSLTemplate);                   \r\n                var newTabCount = this.N" +
                        "ewTabCount;\r\n                newestItems = this.resultNew.sort(function(obj1, ob" +
                        "j2) {                       \r\n                    return new Date(obj2.DateModif" +
                        "ied) - new Date(obj1.DateModified);\r\n                });\r\n                this.A" +
                        "ddItemsToTab(\'newest\',newestItems,newTabCount,newTabIndex,liTemplate,me);       " +
                        "             \r\n\r\n                var recentTabCount = this.RecentTabCount;\r\n    " +
                        "            recentItems = this.resultRecent.sort(function(obj1, obj2) {         " +
                        "              \r\n                    return new Date(obj2.DateModified) - new Dat" +
                        "e(obj1.DateModified);\r\n                });\r\n                this.AddItemsToTab(\'" +
                        "recent\',recentItems,recentTabCount,recentTabIndex,liTemplate,me);               " +
                        "\r\n\r\n                popularItems = this.resultPopular.sort(function(obj1, obj2) " +
                        "{                       \r\n                    return new Date(obj2.TotalLogs) - " +
                        "new Date(obj1.TotalLogs);\r\n                });\r\n\r\n                var popularTab" +
                        "Count = this.PopularTabCount;\r\n                this.AddItemsToTab(\'popular\',popu" +
                        "larItems,popularTabCount,popularTabIndex,liTemplate,me);\r\n                    \r\n" +
                        "                var recommendedTabCount = this.RecommendedTabCount;\r\n           " +
                        "     this.AddItemsToTab(\'recommended\',this.resultRecommended,recommendedTabCount" +
                        ",recommendedTabIndex,liTemplate,me);                                            " +
                        "                                     \r\n                                       \r\n" +
                        "                this.ApplyFinalJS();                   \r\n                    \r\n " +
                        "               if (me.CurrentSite)\r\n                {\r\n                    $(me." +
                        "targetDiv).find(\'table.ia-site-summary-list td:nth-child(2),table.ia-site-summar" +
                        "y-list th:nth-child(2)\').hide();\r\n                }\r\n            };\r\n\r\n         " +
                        "   this.ApplyFinalJS = function(){\r\n                //Tabs selection\r\n          " +
                        "      $.getScript(resourcePathValue + \'/js/components/ia-transformer-tabs.js\');\r" +
                        "\n                //Sorter\r\n                $(\'.ia-site-summary-list\').addClass(\'" +
                        "tablesorter\')\r\n                $(\'.ia-site-summary-list\').tablesorter();\r\n      " +
                        "          //hide tabs not informed\r\n                $(\'.ia-transformer-tab-nav l" +
                        "i a\').each(function(){if($(this).html() ==\'\'){$(this).hide();}})\r\n            }\r" +
                        "\n          \r\n            this.getCellValueByKey = function(results, key) {\r\n    " +
                        "            var result = \"\";\r\n                for (i = 0; i < results.length; i+" +
                        "+) {\r\n                    if (results[i].Key == key) {\r\n                        " +
                        "result = results[i].Value;\r\n                        break;\r\n                    " +
                        "}\r\n                }\r\n                return result;\r\n            };\r\n          " +
                        "  \r\n        };\r\n    }\r\n    \r\n    \r\n \r\n\r\n    $(document).ready(function() {\r\n    " +
                        "    \r\n\r\n        $.ajaxSetup({\r\n            cache: true\r\n        });\r\n       \r\n  " +
                        "      \r\n        var thisDSL = new Akumina.InterAction.DSL();        \r\n        //" +
                        "thisDSL.templateJson = "));
            global::System.Web.UI.WebControls.Literal @__ctrl7;
            @__ctrl7 = this.@__BuildControllitTemplates();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";\r\n        thisDSL.resultNew = "));
            global::System.Web.UI.WebControls.Literal @__ctrl8;
            @__ctrl8 = this.@__BuildControllitResultNew();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisDSL.resultRecent = "));
            global::System.Web.UI.WebControls.Literal @__ctrl9;
            @__ctrl9 = this.@__BuildControllitResultRecent();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisDSL.resultPopular = "));
            global::System.Web.UI.WebControls.Literal @__ctrl10;
            @__ctrl10 = this.@__BuildControllitResultPopular();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisDSL.resultRecommended = "));
            global::System.Web.UI.WebControls.Literal @__ctrl11;
            @__ctrl11 = this.@__BuildControllitResultRecommended();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisDSL.tabNames = "));
            global::System.Web.UI.WebControls.Literal @__ctrl12;
            @__ctrl12 = this.@__BuildControllitTabNames();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisDSL.NewTabDescription = "));
            global::System.Web.UI.WebControls.Literal @__ctrl13;
            @__ctrl13 = this.@__BuildControlNewTabDescription();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisDSL.NewTabCount = "));
            global::System.Web.UI.WebControls.Literal @__ctrl14;
            @__ctrl14 = this.@__BuildControlNewTabCount();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("; \r\n        thisDSL.RecentTabDescription = "));
            global::System.Web.UI.WebControls.Literal @__ctrl15;
            @__ctrl15 = this.@__BuildControlRecentTabDescription();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisDSL.RecentTabCount = "));
            global::System.Web.UI.WebControls.Literal @__ctrl16;
            @__ctrl16 = this.@__BuildControlRecentTabCount();
            @__parser.AddParsedSubObject(@__ctrl16);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("; \r\n        thisDSL.PopularTabDescription = "));
            global::System.Web.UI.WebControls.Literal @__ctrl17;
            @__ctrl17 = this.@__BuildControlPopularTabDescription();
            @__parser.AddParsedSubObject(@__ctrl17);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisDSL.PopularTabCount = "));
            global::System.Web.UI.WebControls.Literal @__ctrl18;
            @__ctrl18 = this.@__BuildControlPopularTabCount();
            @__parser.AddParsedSubObject(@__ctrl18);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("; \r\n        thisDSL.RecommendedTabDescription = "));
            global::System.Web.UI.WebControls.Literal @__ctrl19;
            @__ctrl19 = this.@__BuildControlRecommendedTabDescription();
            @__parser.AddParsedSubObject(@__ctrl19);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisDSL.RecommendedTabCount = "));
            global::System.Web.UI.WebControls.Literal @__ctrl20;
            @__ctrl20 = this.@__BuildControlRecommendedTabCount();
            @__parser.AddParsedSubObject(@__ctrl20);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("; \r\n        thisDSL.CurrentSite = "));
            global::System.Web.UI.WebControls.Literal @__ctrl21;
            @__ctrl21 = this.@__BuildControllitCurrentSite();
            @__parser.AddParsedSubObject(@__ctrl21);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("; \r\n        \r\n        thisDSL.getSearchResultsUsingREST(thisDSL);\r\n\r\n        \r\n  " +
                        "      \r\n    });\r\n</script>\r\n\r\n\r\n\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
