//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akumina.WebParts.QuickLinks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Akumina.WebParts.QuickLinks.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/ia-interaction-controls.css.
        /// </summary>
        internal static string CssLibrary {
            get {
                return ResourceManager.GetString("CssLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;interAction&quot;&gt;    
        ///    &lt;nav class=&quot;ia-top-nav&quot;&gt;
        ///        &lt;ul&gt;
        ///            {{#Items}}
        ///            {{^HasLinks}}
        ///            {{#HasCategories}}
        ///            &lt;li&gt;
        ///                &lt;span class=&quot;ia-dropdown-trigger&quot;&gt;{{Title}}&lt;/span&gt;                
        ///                    
        ///                        &lt;ul&gt;                            
        ///                            {{#Items}}
        ///                            
        ///                            {{#IsItem}}
        ///                            &lt;li&gt;&lt;a href=&quot;{{Link}}&quot; target=&quot;{{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemDetailTemplate {
            get {
                return ResourceManager.GetString("ItemDetailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;interAction&quot;&gt;
        ///		{{#ShowHeader}}
        ///		&lt;div class=&quot;ia-control-header&quot;&gt;
        ///			&lt;span class=&quot;ia-control-header-icon fa fa-{{WebPartIcon}}&quot;&gt;&lt;/span&gt;
        ///			&lt;h3 class=&quot;ia-control-header-heading&quot;&gt;{{Title}}&lt;/h3&gt;
        ///		&lt;/div&gt;
        ///		{{/ShowHeader}}
        ///		&lt;section class=&quot;ia-quicklinks&quot;&gt;			
        ///			&lt;nav class=&quot;ia-quicklinks-nav&quot;&gt;
        ///                &lt;ul class=&quot;ia-quicklinks-level-1&quot;&gt;
        ///                    {{#Items}}
        ///                    {{^HasLinks}}
        ///                    {{#HasCategories}}
        ///                    &lt;li&gt;
        ///                     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemTemplate {
            get {
                return ResourceManager.GetString("ItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;interAction&quot;&gt;
        ///    &lt;nav class=&quot;ia-dept-nav&quot;&gt;
        ///        &lt;div class=&quot;ia-dept-nav-trigger&quot;&gt;&lt;span class=&quot;fa fa-bars ia-dept-nav-icon&quot;&gt;&lt;/span&gt;{{Title}}&lt;/div&gt;
        ///    &lt;/nav&gt;&lt;!-- end mainNav--&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;interAction&quot;&gt;
        ///    &lt;div class=&quot;ia-dept-nav-wrapper&quot;&gt;
        ///        &lt;div class=&quot;ia-dept-nav-menu&quot;&gt;
        ///            &lt;span class=&quot;fa fa-times ia-dept-nav-close&quot;&gt;&lt;/span&gt;
        ///            &lt;ul&gt;
        ///                {{#Items}}
        ///                {{^HasLinks}}
        ///                {{#HasCategories}}
        ///                &lt;li&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemTemplateSubSite {
            get {
                return ResourceManager.GetString("ItemTemplateSubSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /js/vendor/jquery-2.1.3.min.js|js/vendor/mustache.min.js|js/controls/ia-quicklinks.js.
        /// </summary>
        internal static string JsLibrary {
            get {
                return ResourceManager.GetString("JsLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akumina InterAction.
        /// </summary>
        internal static string PropertyGroup {
            get {
                return ResourceManager.GetString("PropertyGroup", resourceCulture);
            }
        }
    }
}
