//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akumina.WebParts.Documents.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Akumina.WebParts.Documents.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string _cloneColumns {
            get {
                return ResourceManager.GetString("_cloneColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All documents, files, and folders in.
        /// </summary>
        public static string breadCrumpText {
            get {
                return ResourceManager.GetString("breadCrumpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string btnCheckIn {
            get {
                return ResourceManager.GetString("btnCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string btnCheckInMore {
            get {
                return ResourceManager.GetString("btnCheckInMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string btnCheckOut {
            get {
                return ResourceManager.GetString("btnCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string btnCheckOutAll {
            get {
                return ResourceManager.GetString("btnCheckOutAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance Details.
        /// </summary>
        public static string btnCompliance {
            get {
                return ResourceManager.GetString("btnCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Link.
        /// </summary>
        public static string btncopyLink {
            get {
                return ResourceManager.GetString("btncopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard checkout.
        /// </summary>
        public static string btnDiscardCheckOut {
            get {
                return ResourceManager.GetString("btnDiscardCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard checkout.
        /// </summary>
        public static string btnDiscardChkOutAll {
            get {
                return ResourceManager.GetString("btnDiscardChkOutAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string btnDoc {
            get {
                return ResourceManager.GetString("btnDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string btnDownload {
            get {
                return ResourceManager.GetString("btnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit properties.
        /// </summary>
        public static string btnEditProperties {
            get {
                return ResourceManager.GetString("btnEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string btnExcelDoc {
            get {
                return ResourceManager.GetString("btnExcelDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow this File.
        /// </summary>
        public static string btnFollow {
            get {
                return ResourceManager.GetString("btnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string btnMore {
            get {
                return ResourceManager.GetString("btnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote.
        /// </summary>
        public static string btnONoteDoc {
            get {
                return ResourceManager.GetString("btnONoteDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string btnOpen {
            get {
                return ResourceManager.GetString("btnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint.
        /// </summary>
        public static string btnPPTDoc {
            get {
                return ResourceManager.GetString("btnPPTDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this File...
        /// </summary>
        public static string btnShare {
            get {
                return ResourceManager.GetString("btnShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is shared With...
        /// </summary>
        public static string btnShareWith {
            get {
                return ResourceManager.GetString("btnShareWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string btnUpload {
            get {
                return ResourceManager.GetString("btnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View properties.
        /// </summary>
        public static string btnViewProperties {
            get {
                return ResourceManager.GetString("btnViewProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string btnWordDoc {
            get {
                return ResourceManager.GetString("btnWordDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows.
        /// </summary>
        public static string btnWorkflow {
            get {
                return ResourceManager.GetString("btnWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.HeaderName.
        /// </summary>
        public static string colName_Grid_Header {
            get {
                return ResourceManager.GetString("colName_Grid_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListName.
        /// </summary>
        public static string colName_ListName {
            get {
                return ResourceManager.GetString("colName_ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.NumberOfPopularFiles.
        /// </summary>
        public static string colName_Popular {
            get {
                return ResourceManager.GetString("colName_Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.NumberOfRecentFiles.
        /// </summary>
        public static string colName_Recent {
            get {
                return ResourceManager.GetString("colName_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RootResourcePath.
        /// </summary>
        public static string colName_RootResourcePath {
            get {
                return ResourceManager.GetString("colName_RootResourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /css/ia-interaction-controls.css|/css/ia-document-grid.css.
        /// </summary>
        public static string CSS_Links {
            get {
                return ResourceManager.GetString("CSS_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Search returned no results!.
        /// </summary>
        public static string Gird_EmptyDataText {
            get {
                return ResourceManager.GetString("Gird_EmptyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |TypeUrl|LinkFilename|Modified|Editor|ID|File_x0020_Type|Path|Status|EditorClone|ModifiedTime|EditPermission.
        /// </summary>
        public static string Grid_Columns {
            get {
                return ResourceManager.GetString("Grid_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name|Modified|Modified By.
        /// </summary>
        public static string Grid_Header_ColumnNames {
            get {
                return ResourceManager.GetString("Grid_Header_ColumnNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /js/vendor/jquery-2.1.3.min.js.
        /// </summary>
        public static string JquerylibraryPath {
            get {
                return ResourceManager.GetString("JquerylibraryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /js/vendor/modernizr.js|/js/controls/ia-document-grid.js|/js/controls/ia-context-menu.js|/js/vendor/quicksearch.js|/js/controls/ia-document-list.js|/js/vendor/jquery.dropdown.js|/js/vendor/jquery.magnific-popup.js|/js/components/modal.js|/js/vendor/jstree.js|/js/controls/ia-drag-drop.js|/js/components/accordion.js|/js/vendor/picker.js|/js/vendor/picker.date.js|/js/vendor/tablesaw.stackonly.js|/js/components/tabs.js.
        /// </summary>
        public static string JS_Links {
            get {
                return ResourceManager.GetString("JS_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string MetaField {
            get {
                return ResourceManager.GetString("MetaField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string preview_Follow {
            get {
                return ResourceManager.GetString("preview_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string preview_Share {
            get {
                return ResourceManager.GetString("preview_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor|File_x0020_Type|Category.
        /// </summary>
        public static string Refiner_Fields {
            get {
                return ResourceManager.GetString("Refiner_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days.
        /// </summary>
        public static string refiner_lstweek {
            get {
                return ResourceManager.GetString("refiner_lstweek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 days.
        /// </summary>
        public static string refiner_month {
            get {
                return ResourceManager.GetString("refiner_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string refiner_today {
            get {
                return ResourceManager.GetString("refiner_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        public static string refiner_year {
            get {
                return ResourceManager.GetString("refiner_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Subfolders.
        /// </summary>
        public static string SearchDropDown_SubFolders {
            get {
                return ResourceManager.GetString("SearchDropDown_SubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Folder.
        /// </summary>
        public static string SearchDropDown_ThisFolder {
            get {
                return ResourceManager.GetString("SearchDropDown_ThisFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Folder|Include SubFolders.
        /// </summary>
        public static string SearchDropDwonOptions {
            get {
                return ResourceManager.GetString("SearchDropDwonOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string Tab_AllFiles_Text {
            get {
                return ResourceManager.GetString("Tab_AllFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Files.
        /// </summary>
        public static string Tab_MyFiles_Text {
            get {
                return ResourceManager.GetString("Tab_MyFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string Tab_PopularFiles_Text {
            get {
                return ResourceManager.GetString("Tab_PopularFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Tab_RecentFiles_Text {
            get {
                return ResourceManager.GetString("Tab_RecentFiles_Text", resourceCulture);
            }
        }
    }
}
