//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Akumina.WebParts.ContentBlock {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Akumina.WebParts.ContentBlock.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;site-alert&quot;&gt;
        ///	&lt;h1&gt;&lt;span class=&quot;fa fa-exclamation-triangle alert-icon&quot;&gt;&lt;/span&gt; Alert:&lt;/h1&gt;
        ///	{{Html}}
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string AlertTemplate {
            get {
                return ResourceManager.GetString("AlertTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /css/ia-interaction-controls.css.
        /// </summary>
        internal static string CssLibrary {
            get {
                return ResourceManager.GetString("CssLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;{{Html}}&lt;/p&gt;
        ///.
        /// </summary>
        internal static string ItemTemplate {
            get {
                return ResourceManager.GetString("ItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /js/vendor/jquery-2.1.3.min.js|/js/vendor/mustache.min.js.
        /// </summary>
        internal static string JsLibrary {
            get {
                return ResourceManager.GetString("JsLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Alert.
        /// </summary>
        internal static string lblDisableAlert {
            get {
                return ResourceManager.GetString("lblDisableAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Query Part.
        /// </summary>
        internal static string lblQueryPart {
            get {
                return ResourceManager.GetString("lblQueryPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site-wide Alert Message.
        /// </summary>
        internal static string lblSiteWideAlert {
            get {
                return ResourceManager.GetString("lblSiteWideAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akumina InterAction.
        /// </summary>
        internal static string PropertyGroup {
            get {
                return ResourceManager.GetString("PropertyGroup", resourceCulture);
            }
        }
    }
}
