//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akumina.WebParts.SiteSummaryList.SiteSummaryList {
    using System.Linq;
    using System.Web.Security;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;
    using System.Web.UI.WebControls;
    using System.Xml.Linq;
    using System.Web.UI;
    using System;
    using System.Web.UI.HtmlControls;
    using System.Web;
    using System.Configuration;
    using System.ComponentModel.DataAnnotations;
    using System.Text;
    using System.Web.Profile;
    using System.Web.Caching;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.WebControls.Expressions;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    using System.Web.DynamicData;
    using System.CodeDom.Compiler;
    
    
    public partial class SiteSummaryList {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litTop;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox controlHtml;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox itemHtml;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litTemplates;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litResultNew;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litResultRecommended;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal litTabNames;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal NewTabDescription;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal NewTabCount;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal RecentTabDescription;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal RecentTabCount;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal PopularTabDescription;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal PopularTabCount;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal RecommendedTabDescription;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Literal RecommendedTabCount;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(SiteSummaryList target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitTop() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litTop = @__ctrl;
            @__ctrl.ID = "litTop";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlcontrolHtml() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.controlHtml = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "controlHtml";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display:none");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlitemHtml() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.itemHtml = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "itemHtml";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display:none");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitTemplates() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litTemplates = @__ctrl;
            @__ctrl.ID = "litTemplates";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitResultNew() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litResultNew = @__ctrl;
            @__ctrl.ID = "litResultNew";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitResultRecommended() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litResultRecommended = @__ctrl;
            @__ctrl.ID = "litResultRecommended";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControllitTabNames() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.litTabNames = @__ctrl;
            @__ctrl.ID = "litTabNames";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlNewTabDescription() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.NewTabDescription = @__ctrl;
            @__ctrl.ID = "NewTabDescription";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlNewTabCount() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.NewTabCount = @__ctrl;
            @__ctrl.ID = "NewTabCount";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlRecentTabDescription() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.RecentTabDescription = @__ctrl;
            @__ctrl.ID = "RecentTabDescription";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlRecentTabCount() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.RecentTabCount = @__ctrl;
            @__ctrl.ID = "RecentTabCount";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlPopularTabDescription() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.PopularTabDescription = @__ctrl;
            @__ctrl.ID = "PopularTabDescription";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlPopularTabCount() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.PopularTabCount = @__ctrl;
            @__ctrl.ID = "PopularTabCount";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlRecommendedTabDescription() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.RecommendedTabDescription = @__ctrl;
            @__ctrl.ID = "RecommendedTabDescription";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Literal @__BuildControlRecommendedTabCount() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.RecommendedTabCount = @__ctrl;
            @__ctrl.ID = "RecommendedTabCount";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::Akumina.WebParts.SiteSummaryList.SiteSummaryList.SiteSummaryList @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<script type=\"text/javascript\">\r\n    if (Akumina === undefined) {\r\n        va" +
                        "r Akumina = {};\r\n    }\r\n    if (Akumina.InterAction === undefined) {\r\n        Ak" +
                        "umina.InterAction = {};\r\n    }\r\n</script>\r\n\r\n"));
            global::System.Web.UI.WebControls.Literal @__ctrl1;
            @__ctrl1 = this.@__BuildControllitTop();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"


<div id=""targetSSL""></div>
<div id=""targetNew""></div>

<script type=""text/javascript"">

    if (typeof jQuery == 'undefined') {
        document.write(""<script type='text/javascript' src='http://code.jquery.com/jquery-2.1.3.min.js'"" + ""/>"");
    }
</script>

"));
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            @__ctrl2 = this.@__BuildControlcontrolHtml();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            @__ctrl3 = this.@__BuildControlitemHtml();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<script type=\"text/javascript\">\r\n    \r\n    if (Akumina.InterAction.SSL === unde" +
                        "fined) {\r\n      \r\n        Akumina.InterAction.SSL = function() {\r\n            th" +
                        "is.targetDiv = \"#targetSSL\";\r\n            this.Url = \"\";\r\n            this.Name " +
                        "= \"\";\r\n            this.Date = \"\";\r\n            \r\n            this.NewTabDescrip" +
                        "tion = \"\";\r\n            this.NewTabCount= \"\";\r\n            this.RecentTabDescrip" +
                        "tion = \"\";\r\n            this.RecentTabCount = \"\";\r\n            this.PopularTabDe" +
                        "scription= \"\";\r\n            this.PopularTabCount = \"\";\r\n            this.Recomme" +
                        "ndedTabDescription = \"\";\r\n            this.RecommendedTabCount = \"\";\r\n          " +
                        "  this.searchResults = {};\r\n            this.templateJson = {}; \r\n            th" +
                        "is.resultNew = {}; \r\n            this.resultRecommended = {}; \r\n            this" +
                        ".tabNames = {};             \r\n            \r\n            \r\n            this.AddIt" +
                        "emsToTab = function(tabName,items,tabCount,tabIndex,liTemplate,me)\r\n            " +
                        "{\r\n\r\n                $.each(items, function(index, result) {\r\n                  " +
                        "  var resultJson = {};\r\n                  \r\n                    resultJson.Name " +
                        "= result.Site;\r\n                    var myDate =\"\";\r\n                    if(resu" +
                        "lt.Date !=\"\"){\r\n                        myDate = new Date(result.Date);\r\n       " +
                        "                 myDate = myDate.format(\"MM/dd/yyyy\");\r\n                    }\r\n " +
                        "                   resultJson.Date = myDate;\r\n                    resultJson.Url" +
                        " = result.Url;\r\n\r\n                    \r\n                    switch(tabName){\r\n  " +
                        "                      case \"recent\":\r\n                            var myDate =\"\"" +
                        ";\r\n                            if(result.latestAccess !=\"\"){\r\n                  " +
                        "              myDate = new Date(result.latestAccess);\r\n                         " +
                        "       myDate = myDate.format(\"MM/dd/yyyy\");\r\n                            }\r\n   " +
                        "                         resultJson.Date = myDate;\r\n                            " +
                        "if(myDate == \'\')\r\n                            {\r\n                               " +
                        " resultJson.Name =\'\';\r\n                            }\r\n                          " +
                        "  break;\r\n                        case \"popular\":\r\n                            r" +
                        "esultJson.Date = result.TotalAccessed;\r\n                            break;\r\n    " +
                        "                    case \"recommended\":\r\n                            resultJson." +
                        "Date = \'\';\r\n                            break;\r\n                        default:" +
                        "\r\n                            resultJson.ModifiedBy = result.ModifiedBy;\r\n      " +
                        "                      break;\r\n                    }                    \r\n       " +
                        "                 \r\n                    var li = liTemplate;\r\n                   " +
                        " if(resultJson.Name !=\"\")\r\n                    {\r\n                        li = M" +
                        "ustache.to_html(liTemplate, resultJson);\r\n                        $(\".tab\" + tab" +
                        "Index, me.targetDiv).append(li);\r\n                    }\r\n                    if(" +
                        "tabCount > 0 && tabCount == (index+1)){\r\n                        return false;\r\n" +
                        "                    }\r\n                });\r\n            }\r\n\r\n\r\n\r\n            thi" +
                        "s.getSearchResultsUsingREST = function(me) {\r\n                var me = this;\r\n  " +
                        "              \r\n                var newTabIndex =-1;\r\n                var recent" +
                        "TabIndex =-1;\r\n                var popularTabIndex =-1;\r\n                var rec" +
                        "ommendedTabIndex =-1;\r\n\r\n\r\n                var results = this.resultNew;\r\n\r\n    " +
                        "            if (results.length == 0) {\r\n                    $(me.targetDiv).html" +
                        "(\"\");\r\n                } else {\r\n                    var searchResultsHtml = \"\";" +
                        "\r\n                    var sslTemplate = $(\'#controlHtml\').val(); //me.templateJs" +
                        "on.ControlTemplate;\r\n                    var liTemplate = $(\'#itemHtml\').val();/" +
                        "/me.templateJson.ItemTemplate;\r\n                    //Template\r\n                " +
                        "    var resultTemplateJson = {};\r\n                    //Tabs Name\r\n             " +
                        "       var newTabDescription = this.NewTabDescription;\r\n                    var " +
                        "recentTabDescription = this.RecentTabDescription;\r\n                    var popul" +
                        "arTabDescription = this.PopularTabDescription;\r\n                    var recommen" +
                        "dedTabDescription = this.RecommendedTabDescription;\r\n                    $.each(" +
                        "me.tabNames, function(index, tab) {\r\n                        var field = \'tab\' +" +
                        " (index + 1) + \'_name\';\r\n                        var fieldDescription = \'tab\' + " +
                        "(index + 1) + \'_description\';\r\n                        var dateDescription = \'ta" +
                        "b\' + (index + 1) + \'_DateDescription\';\r\n                        resultTemplateJs" +
                        "on[field] = tab;\r\n                        \r\n                        switch(tab.t" +
                        "oLowerCase().replace(\' \',\'\'))\r\n                        {\r\n                      " +
                        "      case \"newest\":\r\n                                newTabIndex= index +1;\r\n  " +
                        "                              resultTemplateJson[fieldDescription] = newTabDescr" +
                        "iption;\r\n                                resultTemplateJson[dateDescription] = \"" +
                        "Date Available\";\r\n                                break;\r\n                      " +
                        "      case \"myrecent\":\r\n                                recentTabIndex= index +1" +
                        ";\r\n                                resultTemplateJson[fieldDescription] =recentT" +
                        "abDescription; \r\n                                resultTemplateJson[dateDescript" +
                        "ion] = \"Last Accessed\";\r\n                                break;\r\n               " +
                        "             case \"popular\":\r\n                                popularTabIndex= i" +
                        "ndex +1;\r\n                                resultTemplateJson[fieldDescription] =" +
                        " popularTabDescription; \r\n                                resultTemplateJson[dat" +
                        "eDescription] = numberOfDaysPopular >0 ? \"# Views Last \" + numberOfDaysPopular +" +
                        " \" days\" : \"# Views Last 30 days\";\r\n                                break;\r\n    " +
                        "                        case \"recommended\":\r\n                                rec" +
                        "ommendedTabIndex= index +1;\r\n                                resultTemplateJson[" +
                        "fieldDescription]= recommendedTabDescription;\r\n                                r" +
                        "esultTemplateJson[dateDescription] = \"\";\r\n                                break;" +
                        "\r\n\r\n                        }\r\n                    });\r\n                    \r\n  " +
                        "                 \r\n\r\n                    sslTemplate = Mustache.to_html(sslTempl" +
                        "ate, resultTemplateJson);\r\n                    \r\n                    $(me.target" +
                        "Div).append(sslTemplate);\r\n                    //New\r\n                    var ne" +
                        "wItems = results[0].Item.sort(function(obj1, obj2) {                       \r\n   " +
                        "                     return new Date(obj2.Date) - new Date(obj1.Date);\r\n        " +
                        "            });\r\n\r\n                    var newTabCount = this.NewTabCount;\r\n    " +
                        "                this.AddItemsToTab(\'newest\',newItems,newTabCount,newTabIndex,liT" +
                        "emplate,me);\r\n                    //My Recent\r\n                    var minDate =" +
                        " new Date(-8640000000000000);\r\n                    \r\n                    var rec" +
                        "entItems = results[0].Item.sort(function(obj1, obj2) {                       \r\n " +
                        "                       return (obj2.latestAccess != \"\" ? new Date(obj2.latestAcc" +
                        "ess) : minDate) -  (obj1.latestAccess != \"\" ? new Date(obj1.latestAccess) : minD" +
                        "ate);\r\n                    });\r\n                    var recentTabCount = this.Re" +
                        "centTabCount;\r\n                    this.AddItemsToTab(\'recent\',recentItems,recen" +
                        "tTabCount,recentTabIndex,liTemplate,me);                                        " +
                        "                                \r\n\r\n\r\n                    //Popular\r\n           " +
                        "         var popularItems = results[0].Item.sort(function(obj1, obj2) {         " +
                        "              \r\n                        return new Date(obj2.TotalAccessed) -  n" +
                        "ew Date(obj1.TotalAccessed);\r\n                    });\r\n                    var p" +
                        "opularTabCount = this.PopularTabCount;\r\n                    this.AddItemsToTab(\'" +
                        "popular\',popularItems,popularTabCount,popularTabIndex,liTemplate,me);\r\n         " +
                        "          \r\n                    //Recommended\r\n                    var recommend" +
                        "edItems = this.resultRecommended[0].Item.sort(function(obj1, obj2) {            " +
                        "           \r\n                        return new Date(obj2.Name) -  new Date(obj1" +
                        ".Name);\r\n                    });\r\n                    var recommendedTabCount = " +
                        "this.RecommendedTabCount;\r\n                    this.AddItemsToTab(\'recommended\'," +
                        "recommendedItems,recommendedTabCount,recommendedTabIndex,liTemplate,me);\r\n      " +
                        "             \r\n                }    \r\n                //Tabs selection\r\n        " +
                        "        $.getScript(resourcePathValue + \'/js/components/ia-transformer-tabs.js\')" +
                        ";\r\n                //Sorter\r\n                $(\'.ia-site-summary-list\').addClass" +
                        "(\'tablesorter\')\r\n                $(\'.ia-site-summary-list\').tablesorter();\r\n    " +
                        "            //hide tabs not informed\r\n                $(\'.ia-transformer-tab-nav" +
                        " li a\').each(function(){if($(this).html() ==\'\'){$(this).parent().remove();}})\r\n " +
                        "               \r\n            };\r\n\r\n          \r\n            this.getCellValueByKe" +
                        "y = function(results, key) {\r\n                var result = \"\";\r\n                " +
                        "for (i = 0; i < results.length; i++) {\r\n                    if (results[i].Key =" +
                        "= key) {\r\n                        result = results[i].Value;\r\n                  " +
                        "      break;\r\n                    }\r\n                }\r\n                return r" +
                        "esult;\r\n            };\r\n            \r\n        };\r\n    }\r\n    \r\n    \r\n   \r\n\r\n\r\n  " +
                        "  $(document).ready(function() {\r\n   \r\n        $.ajaxSetup({\r\n            cache:" +
                        " true\r\n        });       \r\n        \r\n        var thisSSL = new Akumina.InterActi" +
                        "on.SSL();        \r\n        //thisSSL.templateJson = "));
            global::System.Web.UI.WebControls.Literal @__ctrl4;
            @__ctrl4 = this.@__BuildControllitTemplates();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";\r\n        thisSSL.resultNew = "));
            global::System.Web.UI.WebControls.Literal @__ctrl5;
            @__ctrl5 = this.@__BuildControllitResultNew();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisSSL.resultRecommended = "));
            global::System.Web.UI.WebControls.Literal @__ctrl6;
            @__ctrl6 = this.@__BuildControllitResultRecommended();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n\r\n        thisSSL.tabNames = "));
            global::System.Web.UI.WebControls.Literal @__ctrl7;
            @__ctrl7 = this.@__BuildControllitTabNames();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisSSL.NewTabDescription = "));
            global::System.Web.UI.WebControls.Literal @__ctrl8;
            @__ctrl8 = this.@__BuildControlNewTabDescription();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisSSL.NewTabCount = "));
            global::System.Web.UI.WebControls.Literal @__ctrl9;
            @__ctrl9 = this.@__BuildControlNewTabCount();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("; \r\n        thisSSL.RecentTabDescription = "));
            global::System.Web.UI.WebControls.Literal @__ctrl10;
            @__ctrl10 = this.@__BuildControlRecentTabDescription();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisSSL.RecentTabCount = "));
            global::System.Web.UI.WebControls.Literal @__ctrl11;
            @__ctrl11 = this.@__BuildControlRecentTabCount();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("; \r\n        thisSSL.PopularTabDescription = "));
            global::System.Web.UI.WebControls.Literal @__ctrl12;
            @__ctrl12 = this.@__BuildControlPopularTabDescription();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisSSL.PopularTabCount = "));
            global::System.Web.UI.WebControls.Literal @__ctrl13;
            @__ctrl13 = this.@__BuildControlPopularTabCount();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("; \r\n        thisSSL.RecommendedTabDescription = "));
            global::System.Web.UI.WebControls.Literal @__ctrl14;
            @__ctrl14 = this.@__BuildControlRecommendedTabDescription();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(";        \r\n        thisSSL.RecommendedTabCount = "));
            global::System.Web.UI.WebControls.Literal @__ctrl15;
            @__ctrl15 = this.@__BuildControlRecommendedTabCount();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("; \r\n        \r\n\r\n        thisSSL.getSearchResultsUsingREST(thisSSL);        \r\n    " +
                        "    \r\n        \r\n    });\r\n</script>\r\n\r\n\r\n\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
